### PR TITLE
Add ASL gesture video samples

### PR DESCRIPTION
**Pull request by evgeny-izutov**

### CODE REVIEW

**Comment by evgeny-izutov** [comment]
@yssemaev, could you please confirm the legal/privacy status.

**Comment by yssemaev** [comment]
Hi,
Self-created datasets with consent forms signed, DSI-821 is WIP.

**Comment by evgeny-izutov** [comment]
@yssemaev, Any updates?

**Comment by yssemaev** [comment]
DSI-821 approved

**Comment by snosov1** [comment]
Can someone, please, merge?

**Comment by vladimir-dudnik** [comment]
who owns and maintain this repo? PR with media files for OpenVINO Open Model Zoo demos can't be even reviewed for a year!

**Pull request merged**
